baseurl = "http://www.freedomjs.org/tutorial/"
languageCode = "en-us"
title = "freedom.js tutorial"

[params]
  defaultDescription = "Tutorial for freedom.js, a framework for peer-to-peer web apps"
  defaultKeywords = "javascript,freedom.js,decentralized,tutorial"
  theme = "theme-base-08"
  github = "https://github.com/freedomjs"
  #googleAnalytics = "Your Google Analytics tracking code"
  frontheader = "A tutorial for freedom.js, a framework for peer-to-peer web apps"
  frontpitch = """
  Want to make a web application that can be easily distributed and hosted statically?
  Want to easily create apps that are social, but let users control their own content?
  freedom.js is a framework for facilitating peer-to-peer applications that run right
  in the browser (or as packaged apps/extensions for a variety of HTML5-type platforms).
  """
  frontdescription = """
  In this tutorial you'll learn about freedom.js, and step through the development of
  Dorabella, a peer-to-peer encrypted chat application developed with freedom.js. This
  tutorial provides all the information a new developer needs to get started - if you
  are already experienced (in particular with the modern JavaScript ecosystem) then some
  sections are marked as "skippable" and you can focus on the parts that are new to you.
  """

[author]
  name = "UW Networks Lab"
